version: '3'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Teste@1234
      - ACCEPT_EULA=Y
    ports:
      - "1500:1433"
    volumes:
      - ./data:/var/opt/mssql/data

# host=127.0.0.1, 1500
# user=sa, 
# senha=Teste@1234
